// <auto-generated />
using System;
using MediaArchive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaArchive.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721103114_MoodsAndSeries")]
    partial class MoodsAndSeries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MediaArchive.Models.ConsumptionEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Context")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Effort")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RatingAtTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserMediaItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserMediaItemId");

                    b.ToTable("ConsumptionEntries");
                });

            modelBuilder.Entity("MediaArchive.Models.EntryNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumptionEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EffortAtTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsumptionEntryId");

                    b.ToTable("EntryNotes");
                });

            modelBuilder.Entity("MediaArchive.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentGenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MediaArchive.Models.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExternalRating")
                        .HasColumnType("REAL");

                    b.Property<int?>("ExternalRatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeriesPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UniverseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("UniverseId");

                    b.ToTable("MediaItems");

                    b.HasDiscriminator<int>("MediaType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MediaArchive.Models.MediaItemGenre", b =>
                {
                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("MediaItemGenre");
                });

            modelBuilder.Entity("MediaArchive.Models.MediaItemMood", b =>
                {
                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mood")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaItemId", "Mood");

                    b.ToTable("MediaItemMood");
                });

            modelBuilder.Entity("MediaArchive.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("MediaArchive.Models.Universe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoreOfTheDayPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Universes");
                });

            modelBuilder.Entity("MediaArchive.Models.UserMediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Discovery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaItemId")
                        .IsUnique();

                    b.ToTable("UserMediaItems");
                });

            modelBuilder.Entity("MediaArchive.Models.Book", b =>
                {
                    b.HasBaseType("MediaArchive.Models.MediaItem");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("MediaArchive.Models.Game", b =>
                {
                    b.HasBaseType("MediaArchive.Models.MediaItem");

                    b.Property<string>("Developer")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeToBeatHours")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("MediaArchive.Models.Movie", b =>
                {
                    b.HasBaseType("MediaArchive.Models.MediaItem");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("MediaArchive.Models.Show", b =>
                {
                    b.HasBaseType("MediaArchive.Models.MediaItem");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Studio")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("MediaArchive.Models.ConsumptionEntry", b =>
                {
                    b.HasOne("MediaArchive.Models.UserMediaItem", "UserMediaItem")
                        .WithMany("Entries")
                        .HasForeignKey("UserMediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserMediaItem");
                });

            modelBuilder.Entity("MediaArchive.Models.EntryNote", b =>
                {
                    b.HasOne("MediaArchive.Models.ConsumptionEntry", "ConsumptionEntry")
                        .WithMany("Notes")
                        .HasForeignKey("ConsumptionEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumptionEntry");
                });

            modelBuilder.Entity("MediaArchive.Models.Genre", b =>
                {
                    b.HasOne("MediaArchive.Models.Genre", "ParentGenre")
                        .WithMany("Subgenres")
                        .HasForeignKey("ParentGenreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGenre");
                });

            modelBuilder.Entity("MediaArchive.Models.MediaItem", b =>
                {
                    b.HasOne("MediaArchive.Models.Series", "Series")
                        .WithMany("Items")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MediaArchive.Models.Universe", "Universe")
                        .WithMany("Items")
                        .HasForeignKey("UniverseId");

                    b.Navigation("Series");

                    b.Navigation("Universe");
                });

            modelBuilder.Entity("MediaArchive.Models.MediaItemGenre", b =>
                {
                    b.HasOne("MediaArchive.Models.Genre", "Genre")
                        .WithMany("MediaItems")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaArchive.Models.MediaItem", "MediaItem")
                        .WithMany("Genres")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("MediaArchive.Models.MediaItemMood", b =>
                {
                    b.HasOne("MediaArchive.Models.MediaItem", "MediaItem")
                        .WithMany("Moods")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("MediaArchive.Models.UserMediaItem", b =>
                {
                    b.HasOne("MediaArchive.Models.MediaItem", "MediaItem")
                        .WithOne("UserMediaItem")
                        .HasForeignKey("MediaArchive.Models.UserMediaItem", "MediaItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("MediaArchive.Models.ConsumptionEntry", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("MediaArchive.Models.Genre", b =>
                {
                    b.Navigation("MediaItems");

                    b.Navigation("Subgenres");
                });

            modelBuilder.Entity("MediaArchive.Models.MediaItem", b =>
                {
                    b.Navigation("Genres");

                    b.Navigation("Moods");

                    b.Navigation("UserMediaItem");
                });

            modelBuilder.Entity("MediaArchive.Models.Series", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MediaArchive.Models.Universe", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MediaArchive.Models.UserMediaItem", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
