using System.Collections;
using System.Reflection;
using System.Text;
using System.Text.Json;
using MediaArchive.Services.Native;

// Emits the Swift side of the native boundary from the C# route table: one
// Codable struct per record, one String-backed enum per enum, and the typed Api.
//
//   dotnet run --project tools/SwiftGen -- native/Sources/Generated/Contracts.swift [--check]

var output = args.FirstOrDefault(a => !a.StartsWith("--"))
             ?? throw new ArgumentException("usage: SwiftGen <output.swift> [--check]");
var check = args.Contains("--check");

var generated = new Generator().Emit(NativeRoutes.All);

if (check)
{
    var current = File.Exists(output) ? File.ReadAllText(output) : "";
    if (current != generated)
    {
        Console.Error.WriteLine($"{output} is out of date with the C# contracts — run scripts/sync-contracts.sh");
        return 1;
    }
    Console.WriteLine("✓ Swift contracts up to date");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);
File.WriteAllText(output, generated);
Console.WriteLine($"✓ wrote {output}");
return 0;

sealed class Generator
{
    private static readonly HashSet<string> Keywords =
    [
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import", "init",
        "inout", "internal", "let", "open", "operator", "private", "protocol", "public", "static", "struct",
        "subscript", "typealias", "var", "break", "case", "continue", "default", "defer", "do", "else",
        "fallthrough", "for", "guard", "if", "in", "repeat", "return", "switch", "where", "while", "as",
        "false", "is", "nil", "self", "super", "throws", "true", "try", "Type", "Self"
    ];

    private readonly SortedDictionary<string, Type> _records = new(StringComparer.Ordinal);
    private readonly SortedDictionary<string, Type> _enums = new(StringComparer.Ordinal);
    private readonly NullabilityInfoContext _nullability = new();

    public string Emit(IReadOnlyList<Route> routes)
    {
        foreach (var route in routes)
        {
            if (route.Args is not null) Collect(route.Args);
            if (route.Result is not null) Collect(route.Result);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by tools/SwiftGen from the C# route table (Services/Native). Do not edit;");
        sb.AppendLine("// run scripts/sync-contracts.sh after changing a record or a route.");
        sb.AppendLine();
        sb.AppendLine("import Foundation");
        sb.AppendLine();

        foreach (var (name, type) in _enums)
        {
            sb.AppendLine($"enum {name}: String, Codable, Hashable, Sendable, CaseIterable {{");
            foreach (var member in Enum.GetNames(type))
                sb.AppendLine($"    case {Escape(Camel(member))} = \"{member}\"");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        foreach (var (name, type) in _records)
        {
            sb.AppendLine($"struct {name}: Codable, Hashable, Sendable {{");
            foreach (var property in Properties(type))
                sb.AppendLine($"    var {Escape(Camel(property.Name))}: {SwiftType(_nullability.Create(property))}");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("struct Api {");
        sb.AppendLine("    let backend: Backend");
        foreach (var route in routes)
        {
            var parameters = route.Args is null ? "" : $"_ args: {route.Args.Name}";
            var payload = route.Args is null ? "NoArgs()" : "args";
            if (route.Result is null)
                sb.AppendLine($"    func {route.SwiftName}({parameters}) async throws {{ try await backend.perform(\"{route.Name}\", {payload}) }}");
            else
                sb.AppendLine($"    func {route.SwiftName}({parameters}) async throws -> {SwiftType(route.Result)} {{ try await backend.call(\"{route.Name}\", {payload}) }}");
        }
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void Collect(Type type)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;

        if (IsScalar(type)) return;

        if (type.IsEnum)
        {
            _enums.TryAdd(type.Name, type);
            return;
        }

        if (ElementType(type) is { } element)
        {
            Collect(element);
            return;
        }

        if (DictionaryValueType(type) is { } value)
        {
            Collect(value);
            return;
        }

        if (!_records.TryAdd(type.Name, type)) return;

        foreach (var property in Properties(type))
            Collect(property.PropertyType);
    }

    private static IEnumerable<PropertyInfo> Properties(Type type) => type
        .GetProperties(BindingFlags.Public | BindingFlags.Instance)
        .Where(p => p.CanRead && p.GetIndexParameters().Length == 0)
        .OrderBy(p => p.MetadataToken);

    private string SwiftType(NullabilityInfo info)
    {
        var type = Nullable.GetUnderlyingType(info.Type) ?? info.Type;
        var optional = info.ReadState == NullabilityState.Nullable || Nullable.GetUnderlyingType(info.Type) is not null;

        string inner;
        if (info.ElementType is { } arrayElement)
            inner = $"[{SwiftType(arrayElement)}]";
        else if (ElementType(type) is not null && info.GenericTypeArguments.Length == 1)
            inner = $"[{SwiftType(info.GenericTypeArguments[0])}]";
        else if (DictionaryValueType(type) is not null && info.GenericTypeArguments.Length == 2)
            inner = $"[String: {SwiftType(info.GenericTypeArguments[1])}]";
        else
            inner = SwiftType(type);

        return optional ? inner + "?" : inner;
    }

    // Result types arrive as bare Types: reference nullability is lost, so a
    // route that can return null reads as non-optional and the bridge treats a
    // literal null reply as an error instead.
    private string SwiftType(Type type)
    {
        if (Nullable.GetUnderlyingType(type) is { } underlying)
            return SwiftType(underlying) + "?";
        if (type == typeof(int) || type == typeof(long) || type == typeof(short)) return "Int";
        if (type == typeof(double) || type == typeof(float) || type == typeof(decimal)) return "Double";
        if (type == typeof(bool)) return "Bool";
        if (type == typeof(string)) return "String";
        if (type == typeof(DateOnly)) return "DateOnly";
        if (type == typeof(DateTime) || type == typeof(DateTimeOffset)) return "Date";
        if (ElementType(type) is { } element) return $"[{SwiftType(element)}]";
        if (DictionaryValueType(type) is { } value) return $"[String: {SwiftType(value)}]";
        return type.Name;
    }

    private static bool IsScalar(Type type) =>
        type.IsPrimitive || type == typeof(string) || type == typeof(decimal)
        || type == typeof(DateOnly) || type == typeof(DateTime) || type == typeof(DateTimeOffset);

    private static Type? ElementType(Type type)
    {
        if (type == typeof(string)) return null;
        if (type.IsArray) return type.GetElementType();
        if (DictionaryValueType(type) is not null) return null;

        var enumerable = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IEnumerable<>)
            ? type
            : type.GetInterfaces().FirstOrDefault(i =>
                i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>));
        return enumerable?.GetGenericArguments()[0];
    }

    private static Type? DictionaryValueType(Type type)
    {
        var dictionary = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IDictionary<,>)
            ? type
            : type.GetInterfaces().FirstOrDefault(i =>
                i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IDictionary<,>));
        return dictionary?.GetGenericArguments()[1];
    }

    // System.Text.Json's own policy, so the Swift names match the wire exactly.
    private static string Camel(string name) => JsonNamingPolicy.CamelCase.ConvertName(name);

    private static string Escape(string name) => Keywords.Contains(name) ? $"`{name}`" : name;
}
