using System.Collections;
using System.Reflection;
using System.Text;
using System.Text.Json;
using MediaArchive.Services.Native;

var output = args.FirstOrDefault(a => !a.StartsWith("--"))
             ?? throw new ArgumentException("usage: SwiftGen <output.swift> [--check]");
var check = args.Contains("--check");

var generated = new Generator().Emit(NativeRoutes.All);

if (check)
{
    var current = File.Exists(output) ? File.ReadAllText(output) : "";
    if (current != generated)
    {
        Console.Error.WriteLine($"{output} is out of date with the C# contracts — run scripts/sync-contracts.sh");
        return 1;
    }
    Console.WriteLine("✓ Swift contracts up to date");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output))!);
File.WriteAllText(output, generated);
Console.WriteLine($"✓ wrote {output}");
return 0;

sealed class Generator
{
    private static readonly HashSet<string> Keywords =
    [
        "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import", "init",
        "inout", "internal", "let", "open", "operator", "private", "protocol", "public", "static", "struct",
        "subscript", "typealias", "var", "break", "case", "continue", "default", "defer", "do", "else",
        "fallthrough", "for", "guard", "if", "in", "repeat", "return", "switch", "where", "while", "as",
        "false", "is", "nil", "self", "super", "throws", "true", "try", "Type", "Self"
    ];

    private static readonly Dictionary<Type, string> Scalars = new()
    {
        [typeof(int)] = "Int", [typeof(long)] = "Int", [typeof(short)] = "Int",
        [typeof(double)] = "Double", [typeof(float)] = "Double", [typeof(decimal)] = "Double",
        [typeof(bool)] = "Bool",
        [typeof(string)] = "String",
        [typeof(DateOnly)] = "DateOnly",
        [typeof(DateTime)] = "Date", [typeof(DateTimeOffset)] = "Date",
    };

    private readonly SortedDictionary<string, Type> _records = new(StringComparer.Ordinal);
    private readonly SortedDictionary<string, Type> _enums = new(StringComparer.Ordinal);
    private readonly NullabilityInfoContext _nullability = new();

    public string Emit(IReadOnlyList<Route> routes)
    {
        foreach (var type in routes.SelectMany(r => new[] { r.Args, r.Result }).OfType<Type>())
            Collect(type);

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by tools/SwiftGen from the C# route table (Services/Native). Do not edit;");
        sb.AppendLine("// run scripts/sync-contracts.sh after changing a record or a route.");
        sb.AppendLine();
        sb.AppendLine("import Foundation");
        sb.AppendLine();

        foreach (var (name, type) in _enums)
            AppendDeclaration(sb, $"enum {name}: String, Codable, Hashable, Sendable, CaseIterable {{",
                Enum.GetNames(type).Select(member => $"    case {Escape(Camel(member))} = \"{member}\""));

        foreach (var (name, type) in _records)
            AppendDeclaration(sb, $"struct {name}: Codable, Hashable, Sendable {{",
                Properties(type).Select(p => $"    var {Escape(Camel(p.Name))}: {SwiftType(_nullability.Create(p))}"));

        AppendApi(sb, routes);
        return sb.ToString();
    }

    private static void AppendDeclaration(StringBuilder sb, string header, IEnumerable<string> members)
    {
        sb.AppendLine(header);
        foreach (var member in members)
            sb.AppendLine(member);
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private void AppendApi(StringBuilder sb, IReadOnlyList<Route> routes)
    {
        sb.AppendLine("struct Api {");
        sb.AppendLine("    let backend: Backend");
        foreach (var route in routes)
            sb.AppendLine(ApiFunction(route));
        sb.AppendLine("}");
    }

    private string ApiFunction(Route route)
    {
        var parameters = route.Args is null ? "" : $"_ args: {route.Args.Name}";
        var payload = route.Args is null ? "NoArgs()" : "args";
        return route.Result is null
            ? $"    func {route.SwiftName}({parameters}) async throws {{ try await backend.perform(\"{route.Name}\", {payload}) }}"
            : $"    func {route.SwiftName}({parameters}) async throws -> {SwiftType(route.Result)} {{ try await backend.call(\"{route.Name}\", {payload}) }}";
    }

    private void Collect(Type type)
    {
        type = Nullable.GetUnderlyingType(type) ?? type;

        if (IsScalar(type)) return;

        if (type.IsEnum)
        {
            _enums.TryAdd(type.Name, type);
            return;
        }

        if (ElementType(type) is { } element)
        {
            Collect(element);
            return;
        }

        if (DictionaryValueType(type) is { } value)
        {
            Collect(value);
            return;
        }

        if (!_records.TryAdd(type.Name, type)) return;

        foreach (var property in Properties(type))
            Collect(property.PropertyType);
    }

    private static IEnumerable<PropertyInfo> Properties(Type type) => type
        .GetProperties(BindingFlags.Public | BindingFlags.Instance)
        .Where(p => p.CanRead && p.GetIndexParameters().Length == 0)
        .OrderBy(p => p.MetadataToken);

    private string SwiftType(NullabilityInfo info)
    {
        var type = Nullable.GetUnderlyingType(info.Type) ?? info.Type;
        var optional = info.ReadState == NullabilityState.Nullable || Nullable.GetUnderlyingType(info.Type) is not null;
        var inner = CollectionSwiftType(info, type) ?? SwiftType(type);
        return optional ? inner + "?" : inner;
    }

    private string? CollectionSwiftType(NullabilityInfo info, Type type)
    {
        if (info.ElementType is { } arrayElement)
            return $"[{SwiftType(arrayElement)}]";
        if (ElementType(type) is not null && info.GenericTypeArguments.Length == 1)
            return $"[{SwiftType(info.GenericTypeArguments[0])}]";
        if (DictionaryValueType(type) is not null && info.GenericTypeArguments.Length == 2)
            return $"[String: {SwiftType(info.GenericTypeArguments[1])}]";
        return null;
    }

    // Result types arrive as bare Types with reference nullability lost, so a route that can return null reads as non-optional.
    private string SwiftType(Type type)
    {
        if (Nullable.GetUnderlyingType(type) is { } underlying)
            return SwiftType(underlying) + "?";
        if (Scalars.TryGetValue(type, out var scalar)) return scalar;
        if (ElementType(type) is { } element) return $"[{SwiftType(element)}]";
        if (DictionaryValueType(type) is { } value) return $"[String: {SwiftType(value)}]";
        return type.Name;
    }

    private static bool IsScalar(Type type) => type.IsPrimitive || Scalars.ContainsKey(type);

    private static Type? ElementType(Type type)
    {
        if (type == typeof(string)) return null;
        if (type.IsArray) return type.GetElementType();
        if (DictionaryValueType(type) is not null) return null;

        var enumerable = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IEnumerable<>)
            ? type
            : type.GetInterfaces().FirstOrDefault(i =>
                i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IEnumerable<>));
        return enumerable?.GetGenericArguments()[0];
    }

    private static Type? DictionaryValueType(Type type)
    {
        var dictionary = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IDictionary<,>)
            ? type
            : type.GetInterfaces().FirstOrDefault(i =>
                i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IDictionary<,>));
        return dictionary?.GetGenericArguments()[1];
    }

    // System.Text.Json's own policy, so the Swift names match the wire exactly.
    private static string Camel(string name) => JsonNamingPolicy.CamelCase.ConvertName(name);

    private static string Escape(string name) => Keywords.Contains(name) ? $"`{name}`" : name;
}
